/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-07-24 02:21:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>마이페이지</title>\r\n");
      out.write("        <link rel=\"icon\" type=\"img/png\" href=\"image/round_logo_whiteBack.svg\">\r\n");
      out.write("        <!--bootstrap-->\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"static/css/mypage.css\">\r\n");
      out.write("        <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("        <script src=\"js/weather.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"noto-sans-kr\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("        <nav>\r\n");
      out.write("            <div class=\"nav_left\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a href=\"mainpage01.html\">\r\n");
      out.write("                        <img src=\"images/nav_logo.svg\" alt=\"플랜트랩 로고\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul class=\"nav_menu\">\r\n");
      out.write("                        <li><a href=\"board_list.html\">커뮤니티</a></li>\r\n");
      out.write("                        <li><a href=\"shopping_main.html\">스토어</a></li>\r\n");
      out.write("                        <div id=\"weather\">\r\n");
      out.write("                            <li id=\"weatherList\">\r\n");
      out.write("                                <img id=\"weatherImg\" src=\"#\" alt=\"날씨 이미지\">\r\n");
      out.write("                                <img id=\"weatherLine\" src=\"images/weatherLine.svg\" alt=\"라인 이미지\">\r\n");
      out.write("                                <p id=\"result\"></p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav_right\">\r\n");
      out.write("                <div class=\"nav_search\">\r\n");
      out.write("                                    <span>\r\n");
      out.write("                                        <svg width=\"25\" height=\"25.5\" viewBox=\"0 0 30 34\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                                            <path d=\"M28.9749 26.5226L23.9072 20.9181L20.0092 19.137C21.3071 17.0958 22.0025 14.6606 22 12.1652C22 5.45727 17.0654 0 11 0C4.93455 0 0 5.45727 0 12.1652C0 18.8731 4.93455 24.3304 11 24.3304C13.276 24.3333 15.4961 23.551 17.3511 22.0925L18.9574 26.3918L24.0249 31.9966C24.3499 32.3561 24.7358 32.6412 25.1604 32.8357C25.5851 33.0303 26.0402 33.1304 26.4998 33.1304C26.9595 33.1305 27.4146 33.0303 27.8393 32.8358C28.2639 32.6413 28.6498 32.3562 28.9748 31.9968C29.2998 31.6374 29.5576 31.2106 29.7335 30.741C29.9094 30.2714 30 29.7681 30 29.2597C30 28.7514 29.9095 28.2481 29.7336 27.7784C29.5577 27.3088 29.2999 26.8821 28.9749 26.5226ZM2 12.1652C2 6.67703 6.03749 2.21185 11 2.21185C15.9625 2.21185 20 6.67703 20 12.1652C20 17.6534 15.9625 22.1185 11 22.1185C6.03749 22.1185 2 17.6534 2 12.1652ZM27.5606 30.4326C27.2791 30.7433 26.8976 30.9177 26.4999 30.9177C26.1022 30.9177 25.7208 30.7433 25.4393 30.4326L20.6535 25.1399L19.1601 21.1424L22.7749 22.7939L27.5607 28.0866C27.8416 28.398 27.9993 28.8198 27.9993 29.2596C27.9993 29.6994 27.8415 30.1213 27.5606 30.4326Z\" fill=\"#878787\"/>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                    <input type=\"text\" id=\"search\" placeholder=\"통합검색\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"member\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li style=\"margin:0;\">\r\n");
      out.write("                            <a href=\"_03_마이페이지_최종+재형님.html\">\r\n");
      out.write("                                <img src=\"images/프로필사진.png\" alt=\"임시 프로필사진\" width=\"40px\" height=\"40px\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"margin-left: 10px; font-size: 1.1rem\">\r\n");
      out.write("                            <script>\r\n");
      out.write("                                const nickname = sessionStorage.getItem(\"login\");\r\n");
      out.write("                                document.write(`<a href=\"_03_마이페이지_최종+재형님.html\" style=\"font-weight:400\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>`);\r\n");
      out.write("                            </script>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"images/Header with images_마이페이지.png\" alt=\"마이페이지 헤더\">\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"container-flex\">\r\n");
      out.write("                <div class=\"profilebox\">\r\n");
      out.write("                    <div class=\"profileicon\">\r\n");
      out.write("                        <div class=\"shareicon\">\r\n");
      out.write("                            <img src=\"images/shareicon.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <img src=\"images/프로필사진.png\" class=\"profile\" alt=\"\" style=\"width: 182.69px;\">\r\n");
      out.write("                        <div class=\"profilename\">\r\n");
      out.write("                            <p style=\"font-size: 25px;\">카리나</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profilemedal\">\r\n");
      out.write("                            <img src=\"images/새싹레벨.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profilelevev\">\r\n");
      out.write("                            <p style=\"font-size: 13px;\">lv.1 새싹</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"margin-top: 20px;\">\r\n");
      out.write("                        <div class=\"heartbookmark\">\r\n");
      out.write("                            <div class=\"heartpart\">\r\n");
      out.write("                                <img src=\"images/filledgreenheart.png\" alt=\"\">\r\n");
      out.write("                                <p style=\"color: #0DA446; font-size: 20px; margin-bottom: 5px;\">3</p>\r\n");
      out.write("                                <p>좋아요</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bookmarkpart\">\r\n");
      out.write("                                <img src=\"images/littlefilledbookmarkicon.png\" alt=\"\">\r\n");
      out.write("                                <p style=\"color: #0DA446; font-size: 20px; margin-bottom: 5px;\">25</p>\r\n");
      out.write("                                <p>스크랩북</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"categorybox\">\r\n");
      out.write("                    <div class=\"mycontent\" style=\"border-bottom: #B5B5B5 1px solid;\"\r\n");
      out.write("                         id=\"mycontentbtn\">\r\n");
      out.write("                        <div class=\"mycontenticon\">\r\n");
      out.write("                            <img src=\"images/내가올린글.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mycontenttxt\">\r\n");
      out.write("                            내가올린글\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"snscontent\"  style=\"border-bottom: #B5B5B5 1px solid;\"\r\n");
      out.write("                         id=\"snscontentbtn\">\r\n");
      out.write("                        <div class=\"snscontenticon\">\r\n");
      out.write("                            <img src=\"images/자랑 사진.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"snspic\">\r\n");
      out.write("                            그린톡\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"myshoppingcontent\"\r\n");
      out.write("                         id=\"shopcontentbtn\">\r\n");
      out.write("                        <div class=\"iconplace\">\r\n");
      out.write("                            <div class=\"myshoppingicon\">\r\n");
      out.write("                                <img src=\"images/마이 쇼핑.png\" alt=\"\" style=\"margin-left: -10px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"myshopping\">\r\n");
      out.write("                            마이 쇼핑\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"radio-group\">\r\n");
      out.write("                    <input type=\"radio\" id=\"contype\" name=\"content\">\r\n");
      out.write("                    <input type=\"radio\" id=\"snstype\" name=\"content\">\r\n");
      out.write("                    <input type=\"radio\" id=\"shoptype\" name=\"content\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contentbox\"  id=\"content-a\">\r\n");
      out.write("                <div class=\"titletext\">Q&A\r\n");
      out.write("                    <table class=\"defaluttext\">\r\n");
      out.write("                        <tr class=\"firstRow\">\r\n");
      out.write("                            <td>제목</td>\r\n");
      out.write("                            <td>작성자</td>\r\n");
      out.write("                            <td>작성일</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <div class=\"titletext\">정보글\r\n");
      out.write("                    <table class=\"defaluttext\">\r\n");
      out.write("                        <tr class=\"firstRow\">\r\n");
      out.write("                            <td>제목</td>\r\n");
      out.write("                            <td>작성자</td>\r\n");
      out.write("                            <td>작성일</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contentbox-sns\" id=\"content-b\" style=\"display: none;\"> <!--클릭시 자랑글 모달 띄우게 가능할까요?-->\r\n");
      out.write("                <!-- <button id=\"createBragBtn\" style=\"width: 300px; height: 250px; border: none; background-color: #ECECEC;\"> -->\r\n");
      out.write("                <!-- <img style=\"margin-top: 30px;\" src=\"images/bx_camera.png\" alt=\"cameraLogo\">\r\n");
      out.write("                <p style=\"margin-top: 10px;\">올린 자랑글이 없습니다.</p> -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img src=\"images/자랑글/rank1main.png\" alt=\"\" style=\"width: 300px; height: 250px; border: none;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button id=\"moveBragBtn\" onclick=\"window.location.href='board_list.html?tab=4'\"\r\n");
      out.write("                        style=\"margin-top: 30px; width: 800px; height: 70px; background-color: #d1eada; border: #B8E2C8 solid 2px;\">\r\n");
      out.write("                    <p style=\"margin-top: 20px; font-weight: bold; font-size: large; color: #27AF5A;\">그린톡 바로가기</p>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contentbox--shopping\" id=\"content-c\" style=\"display: none;\">\r\n");
      out.write("                <div id=\"purchaseProcess\">\r\n");
      out.write("                    <ul style=\"list-style: none; display: flex; margin-top: 20px;\">\r\n");
      out.write("                        <li>입금대기\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>결제완료\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>배송준비\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>배송중\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>배송완료\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li style=\"color: #27AF5A; font-weight: bold;\">구매확정\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>2</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"shoppingmenu\">\r\n");
      out.write("                    <span style=\"font-size: 18px;\">구매확정 목록</span>\r\n");
      out.write("                    <span>\r\n");
      out.write("                                    <div class=\"shoppingdrop\">\r\n");
      out.write("                                        <select name=\"purchaseTime\" id=\"purchaseTime\" style=\"width: 100px; margin-top: -15px;\">\r\n");
      out.write("                                            <option value=\"1개월 전\">1개월 전</option>\r\n");
      out.write("                                            <option value=\"3개월 전\" selected>3개월 전</option>\r\n");
      out.write("                                            <option value=\"6개월 전\">6개월 전</option>\r\n");
      out.write("                                            <option value=\"1년 전\">1년 전</option>\r\n");
      out.write("                                            <option value=\"2년 전\">2년 전</option>\r\n");
      out.write("                                            <option value=\"3년 전\">3년 전</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"margin-top: 5px; width: 750px; height: 510px; background-color: #F5F7F6; border: solid #B5B5B5 1px;\">\r\n");
      out.write("                    <!-- 1번 -->\r\n");
      out.write("                    <div style=\"margin-top: 20px; margin-left: 30px; display: flex; justify-content: space-between;\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                                            <span style=\"font-weight: bold; font-size: 15px; margin: 5px;\">구매확정\r\n");
      out.write("                                            </span>\r\n");
      out.write("                            <img src=\"images/Ellipse 16.svg\" alt=\"EllipseImg\">\r\n");
      out.write("                            <span style=\"font-size: 15px; margin: 5px; \">6/13(목) 도착완료</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"button\" style=\"margin-right: 20px; color: #23C961;\">배송 조회 ></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"margin: 20px; display: flex; flex-direction: row; border-bottom: solid 1px gray;\">\r\n");
      out.write("                                        <span style=\"margin: 10px; margin-top: 0px;\">\r\n");
      out.write("                                            <button type=\"button\" style=\"width: 170px; height: 130px; background-color: rgb(164, 161, 161); padding: 0%; border: none; border-radius: 7px;\">\r\n");
      out.write("                                                <!-- 나중에 쇼핑목록 이미지를 연결하기 -->\r\n");
      out.write("                                                <img style=\"width: 100%; height: auto; object-fit: cover; border-radius: 7px;\" src=\"images/purchaseEX01.svg\" alt=\"purchaseEXImg\">\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                        <div style=\"width: 100%; height: 100%;\">\r\n");
      out.write("                            <p style=\"font-weight: bold;\">진한 꽃향기 오렌지 자스민 실내공기정화 식물 인테리어식물<br>플랜테리어 화분</p>\r\n");
      out.write("                            <p style=\"margin-bottom: 0px;\">1차옵션:오렌지 자스민 소 / 2차옵션: 없음</p>\r\n");
      out.write("                            <p>8,900원</p>\r\n");
      out.write("                            <div style=\"display: flex; justify-content: end; margin-bottom: 15px;\">\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn1\" style=\"width: 130px; height: 40px; margin-right: 10px; border: 1px solid #23C961; border-radius: 5px;\">문의</button>\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn2\" style=\"width: 130px; height: 40px; margin-left: 10px; border: 1px solid #23C961; border-radius: 5px;\">리뷰작성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 2번 -->\r\n");
      out.write("                    <div style=\"margin-top: 20px; margin-left: 30px; display: flex; justify-content: space-between;\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                                            <span id=\"purchaseConfirm\" style=\"font-weight: bold; font-size: 15px; margin: 5px;\">구매확정\r\n");
      out.write("                                            </span>\r\n");
      out.write("                            <img src=\"images/Ellipse 16.svg\" alt=\"EllipseImg\">\r\n");
      out.write("                            <span style=\"font-size: 15px; margin: 5px; \">6/13(목) 도착완료</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"button\" style=\"margin-right: 20px; color: #23C961;\">배송 조회 ></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"margin: 20px; display: flex; flex-direction: row;\">\r\n");
      out.write("                                        <span style=\"margin: 10px; margin-top: 0px;\">\r\n");
      out.write("                                            <button type=\"button\" style=\"width: 170px; height: 130px; background-color: rgb(164, 161, 161); padding: 0%; border: none; border-radius: 7px;\">\r\n");
      out.write("                                                <!-- 나중에 쇼핑목록 이미지를 연결하기 -->\r\n");
      out.write("                                                <img style=\"width: 100%; height: auto; object-fit: cover; border-radius: 7px;\" src=\"images/purchaseEX02.svg\" alt=\"purchaseEXImg\">\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                        <div style=\"width: 100%; height: 100%;\">\r\n");
      out.write("                            <p style=\"font-weight: bold;\">진한 꽃향기 오렌지 자스민 실내공기정화 식물 인테리어식물<br>플랜테리어 화분</p>\r\n");
      out.write("                            <p style=\"margin-bottom: 0px;\">1차옵션:오렌지 자스민 대 / 2차옵션: 없음</p>\r\n");
      out.write("                            <p class=\"price\">28,900원</p>\r\n");
      out.write("                            <div style=\"display: flex; justify-content: end; margin-bottom: 15px;\">\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn1\" style=\"width: 130px; height: 40px; margin-right: 10px; border: 1px solid #23C961; border-radius: 5px;\">문의</button>\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn2\" style=\"width: 130px; height: 40px; margin-left: 10px; border: 1px solid #23C961; border-radius: 5px;\">리뷰작성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"popup-icon1\">\r\n");
      out.write("            <img src=\"images/챗봇아이콘.png\" alt=\"Popup Icon\" style=\"width: 60px; height: 60px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"popup-content1\" class=\"hidden\">\r\n");
      out.write("            <p>안녕하세요! 플랜트 봇 입니다!<br>궁금한 것은 모두 플랜트 봇에게 물어보세요!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"popup-icon2\">\r\n");
      out.write("            <img src=\"images/top아이콘.png\" alt=\"Popup Icon\" style=\"width: 60px; height: 60px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("                const popupIcon = document.getElementById('popup-icon1');\r\n");
      out.write("                const popupContent = document.getElementById('popup-content1');\r\n");
      out.write("                const popupIcon2 = document.getElementById('popup-icon2');\r\n");
      out.write("\r\n");
      out.write("                popupIcon.addEventListener('mouseover', () => {\r\n");
      out.write("                    popupContent.classList.remove('hidden');\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                popupIcon.addEventListener('mouseleave', () => {\r\n");
      out.write("                    popupContent.classList.add('hidden');\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                popupIcon2.addEventListener('click', () => {\r\n");
      out.write("                    window.scrollTo({ top: 0, behavior: 'smooth' });\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(() => {\r\n");
      out.write("                $(\"#mycontentbtn\").addClass(\"active\");\r\n");
      out.write("                $(\".mycontenttxt\").css(\"color\", \"white\");\r\n");
      out.write("                $(\"#mycontentbtn\").click((e) => {\r\n");
      out.write("                    $(\"#mycontentbtn\").addClass(\"active\");\r\n");
      out.write("                    $(\"#snscontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#shopcontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#contype\").trigger(\"click\");\r\n");
      out.write("                    $(\".mycontenttxt\").css(\"color\", \"white\");\r\n");
      out.write("                    $(\".snspic\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".myshopping\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\"#content-a\").show();\r\n");
      out.write("                    $(\"#content-b\").hide();\r\n");
      out.write("                    $(\"#content-c\").hide();\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#snscontentbtn\").click((e) => {\r\n");
      out.write("                    $(\"#mycontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#snscontentbtn\").addClass(\"active\");\r\n");
      out.write("                    $(\"#shopcontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#snstype\").trigger(\"click\");\r\n");
      out.write("                    $(\".mycontenttxt\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".snspic\").css(\"color\", \"white\");\r\n");
      out.write("                    $(\".myshopping\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\"#content-a\").hide();\r\n");
      out.write("                    $(\"#content-b\").show();\r\n");
      out.write("                    $(\"#content-c\").hide();\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#shopcontentbtn\").click((e) => {\r\n");
      out.write("                    $(\"#mycontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#snscontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#shopcontentbtn\").addClass(\"active\");\r\n");
      out.write("                    $(\"#shoptype\").trigger(\"click\");\r\n");
      out.write("                    $(\".mycontenttxt\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".snspic\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".myshopping\").css(\"color\", \"white\");\r\n");
      out.write("                    $(\"#content-a\").hide();\r\n");
      out.write("                    $(\"#content-b\").hide();\r\n");
      out.write("                    $(\"#content-c\").show();\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
