/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-07-26 04:30:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>마이페이지</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mypage.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"noto-sans-kr\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <img src=\"static/images/Header with image_마이페이지.png\" alt=\"마이페이지 헤더\">\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"container-flex\">\r\n");
      out.write("                <div class=\"profilebox\">\r\n");
      out.write("                    <div class=\"profileicon\">\r\n");
      out.write("                        <div class=\"shareicon\">\r\n");
      out.write("                            <img src=\"static/images/shareicon.png\" alt=\"프로필수정아이콘\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <img src=\"static/images/프로필사진.png\" class=\"profile\" alt=\"\" style=\"width: 182.69px;\">\r\n");
      out.write("                        <div class=\"profilename\">\r\n");
      out.write("                            <p style=\"font-size: 25px;\">카리나</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profilemedal\">\r\n");
      out.write("                            <img src=\"static/images/새싹레벨.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profilelevev\">\r\n");
      out.write("                            <p style=\"font-size: 13px;\">lv.1 새싹</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"margin-top: 20px;\">\r\n");
      out.write("                        <div class=\"heartbookmark\">\r\n");
      out.write("                            <div class=\"heartpart\">\r\n");
      out.write("                                <img src=\"static/images/filledgreenheart.png\" alt=\"\">\r\n");
      out.write("                                <p style=\"color: #0DA446; font-size: 20px; margin-bottom: 5px;\">3</p>\r\n");
      out.write("                                <p>좋아요</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bookmarkpart\">\r\n");
      out.write("                                <img src=\"static/images/littlefilledbookmarkicon.png\" alt=\"\">\r\n");
      out.write("                                <p style=\"color: #0DA446; font-size: 20px; margin-bottom: 5px;\">25</p>\r\n");
      out.write("                                <p>스크랩북</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"categorybox\">\r\n");
      out.write("                    <div class=\"mycontent\" style=\"border-bottom: #B5B5B5 1px solid;\"\r\n");
      out.write("                         id=\"mycontentbtn\">\r\n");
      out.write("                        <div class=\"mycontenticon\">\r\n");
      out.write("                            <img src=\"static/images/내가올린글.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mycontenttxt\">\r\n");
      out.write("                            내가올린글\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"snscontent\"  style=\"border-bottom: #B5B5B5 1px solid;\"\r\n");
      out.write("                         id=\"snscontentbtn\">\r\n");
      out.write("                        <div class=\"snscontenticon\">\r\n");
      out.write("                            <img src=\"static/images/자랑 사진.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"snspic\">\r\n");
      out.write("                            그린톡\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"myshoppingcontent\"\r\n");
      out.write("                         id=\"shopcontentbtn\">\r\n");
      out.write("                        <div class=\"iconplace\">\r\n");
      out.write("                            <div class=\"myshoppingicon\">\r\n");
      out.write("                                <img src=\"static/images/마이 쇼핑.png\" alt=\"\" style=\"margin-left: -10px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"myshopping\">\r\n");
      out.write("                            마이 쇼핑\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"radio-group\">\r\n");
      out.write("                    <input type=\"radio\" id=\"contype\" name=\"content\">\r\n");
      out.write("                    <input type=\"radio\" id=\"snstype\" name=\"content\">\r\n");
      out.write("                    <input type=\"radio\" id=\"shoptype\" name=\"content\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contentbox\"  id=\"content-a\">\r\n");
      out.write("                <div class=\"titletext\">Q&A\r\n");
      out.write("                    <table class=\"defaluttext\">\r\n");
      out.write("                        <tr class=\"firstRow\">\r\n");
      out.write("                            <td>제목</td>\r\n");
      out.write("                            <td>작성자</td>\r\n");
      out.write("                            <td>작성일</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <div class=\"titletext\">정보글\r\n");
      out.write("                    <table class=\"defaluttext\">\r\n");
      out.write("                        <tr class=\"firstRow\">\r\n");
      out.write("                            <td>제목</td>\r\n");
      out.write("                            <td>작성자</td>\r\n");
      out.write("                            <td>작성일</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Project Name</td>\r\n");
      out.write("                            <td>Name</td>\r\n");
      out.write("                            <td>2022.00.00</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contentbox-sns\" id=\"content-b\" style=\"display: none;\"> <!--클릭시 자랑글 모달 띄우게 가능할까요?-->\r\n");
      out.write("                <!-- <button id=\"createBragBtn\" style=\"width: 300px; height: 250px; border: none; background-color: #ECECEC;\"> -->\r\n");
      out.write("                <!-- <img style=\"margin-top: 30px;\" src=\"images/bx_camera.png\" alt=\"cameraLogo\">\r\n");
      out.write("                <p style=\"margin-top: 10px;\">올린 자랑글이 없습니다.</p> -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img src=\"static/images/자랑글/rank1main.png\" alt=\"\" style=\"width: 300px; height: 250px; border: none;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button id=\"moveBragBtn\" onclick=\"window.location.href='board_list.html?tab=4'\"\r\n");
      out.write("                        style=\"margin-top: 30px; width: 800px; height: 70px; background-color: #d1eada; border: #B8E2C8 solid 2px;\">\r\n");
      out.write("                    <p style=\"margin-top: 20px; font-weight: bold; font-size: large; color: #27AF5A;\">그린톡 바로가기</p>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contentbox--shopping\" id=\"content-c\" style=\"display: none;\">\r\n");
      out.write("                <div id=\"purchaseProcess\">\r\n");
      out.write("                    <ul style=\"list-style: none; display: flex; margin-top: 20px;\">\r\n");
      out.write("                        <li>입금대기\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"static/images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>결제완료\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"static/images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>배송준비\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"static/images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>배송중\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"static/images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li>배송완료\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>0</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <img src=\"static/images/fluent_ios-arrow-24-filled.svg\" alt=\"arrowImg\">\r\n");
      out.write("                        <li style=\"color: #27AF5A; font-weight: bold;\">구매확정\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <span>2</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"shoppingmenu\">\r\n");
      out.write("                    <span style=\"font-size: 18px;\">구매확정 목록</span>\r\n");
      out.write("                    <span>\r\n");
      out.write("                        <div class=\"shoppingdrop\">\r\n");
      out.write("                            <select name=\"purchaseTime\" id=\"purchaseTime\" style=\"width: 100px; margin-top: -15px;\">\r\n");
      out.write("                                <option value=\"1개월 전\">1개월 전</option>\r\n");
      out.write("                                <option value=\"3개월 전\" selected>3개월 전</option>\r\n");
      out.write("                                <option value=\"6개월 전\">6개월 전</option>\r\n");
      out.write("                                <option value=\"1년 전\">1년 전</option>\r\n");
      out.write("                                <option value=\"2년 전\">2년 전</option>\r\n");
      out.write("                                <option value=\"3년 전\">3년 전</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"margin-top: 5px; width: 750px; height: 510px; background-color: #F5F7F6; border: solid #B5B5B5 1px;\">\r\n");
      out.write("                    <!-- 1번 -->\r\n");
      out.write("                    <div style=\"margin-top: 20px; margin-left: 30px; display: flex; justify-content: space-between;\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span style=\"font-weight: bold; font-size: 15px; margin: 5px;\">구매확정\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <img src=\"static/images/Ellipse 16.svg\" alt=\"EllipseImg\">\r\n");
      out.write("                            <span style=\"font-size: 15px; margin: 5px; \">6/13(목) 도착완료</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"button\" style=\"margin-right: 20px; color: #23C961;\">배송 조회 ></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"margin: 20px; display: flex; flex-direction: row; border-bottom: solid 1px gray;\">\r\n");
      out.write("                        <span style=\"margin: 10px; margin-top: 0px;\">\r\n");
      out.write("                            <button type=\"button\" style=\"width: 170px; height: 130px; background-color: rgb(164, 161, 161); padding: 0%; border: none; border-radius: 7px;\">\r\n");
      out.write("                                <!-- 나중에 쇼핑목록 이미지를 연결하기 -->\r\n");
      out.write("                                <img style=\"width: 100%; height: auto; object-fit: cover; border-radius: 7px;\" src=\"static/images/purchaseEX01.svg\" alt=\"purchaseEXImg\">\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div style=\"width: 100%; height: 100%;\">\r\n");
      out.write("                            <p style=\"font-weight: bold;\">진한 꽃향기 오렌지 자스민 실내공기정화 식물 인테리어식물<br>플랜테리어 화분</p>\r\n");
      out.write("                            <p style=\"margin-bottom: 0px;\">1차옵션:오렌지 자스민 소 / 2차옵션: 없음</p>\r\n");
      out.write("                            <p>8,900원</p>\r\n");
      out.write("                            <div style=\"display: flex; justify-content: end; margin-bottom: 15px;\">\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn1\" style=\"width: 130px; height: 40px; margin-right: 10px; border: 1px solid #23C961; border-radius: 5px;\">문의</button>\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn2\" style=\"width: 130px; height: 40px; margin-left: 10px; border: 1px solid #23C961; border-radius: 5px;\">리뷰작성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 2번 -->\r\n");
      out.write("                    <div style=\"margin-top: 20px; margin-left: 30px; display: flex; justify-content: space-between;\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span id=\"purchaseConfirm\" style=\"font-weight: bold; font-size: 15px; margin: 5px;\">구매확정\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <img src=\"static/images/Ellipse 16.svg\" alt=\"EllipseImg\">\r\n");
      out.write("                            <span style=\"font-size: 15px; margin: 5px; \">6/13(목) 도착완료</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"button\" style=\"margin-right: 20px; color: #23C961;\">배송 조회 ></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"margin: 20px; display: flex; flex-direction: row;\">\r\n");
      out.write("                        <span style=\"margin: 10px; margin-top: 0px;\">\r\n");
      out.write("                            <button type=\"button\" style=\"width: 170px; height: 130px; background-color: rgb(164, 161, 161); padding: 0%; border: none; border-radius: 7px;\">\r\n");
      out.write("                                <!-- 나중에 쇼핑목록 이미지를 연결하기 -->\r\n");
      out.write("                                <img style=\"width: 100%; height: auto; object-fit: cover; border-radius: 7px;\" src=\"static/images/purchaseEX02.svg\" alt=\"purchaseEXImg\">\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div style=\"width: 100%; height: 100%;\">\r\n");
      out.write("                            <p style=\"font-weight: bold;\">진한 꽃향기 오렌지 자스민 실내공기정화 식물 인테리어식물<br>플랜테리어 화분</p>\r\n");
      out.write("                            <p style=\"margin-bottom: 0px;\">1차옵션:오렌지 자스민 대 / 2차옵션: 없음</p>\r\n");
      out.write("                            <p class=\"price\">28,900원</p>\r\n");
      out.write("                            <div style=\"display: flex; justify-content: end; margin-bottom: 15px;\">\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn1\" style=\"width: 130px; height: 40px; margin-right: 10px; border: 1px solid #23C961; border-radius: 5px;\">문의</button>\r\n");
      out.write("                                <button type=\"button\" class=\"purbtn2\" style=\"width: 130px; height: 40px; margin-left: 10px; border: 1px solid #23C961; border-radius: 5px;\">리뷰작성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"popup-icon1\">\r\n");
      out.write("            <img src=\"static/images/챗봇아이콘.png\" alt=\"Popup Icon\" style=\"width: 60px; height: 60px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"popup-content1\" class=\"hidden\">\r\n");
      out.write("            <p>안녕하세요! 플랜트 봇 입니다!<br>궁금한 것은 모두 플랜트 봇에게 물어보세요!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"popup-icon2\">\r\n");
      out.write("            <img src=\"static/images/top아이콘.png\" alt=\"Popup Icon\" style=\"width: 60px; height: 60px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div id=\"modal-close-btn\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" id=\"modal-close-btn-detail\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"profilebox-header\">\r\n");
      out.write("                        <div style=\"margin-top: 7vh\">\r\n");
      out.write("                            <div id=\"modify-profile-image\" style=\"position: relative; display: inline-block;\">\r\n");
      out.write("                                <img src=\"static/images/프로필사진.png\" class=\"profile\" alt=\"프로필사진\" style=\"width: 8vw; height: auto\">\r\n");
      out.write("                                <button type=\"button\" style=\"position: absolute; bottom: 0; right: 0;\"><img src=\"static/images/modify_profile.svg\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" style=\"align-items: center; font-size: 0.8rem; color: #CCCCCC; margin-top: 1vh\">이미지 삭제</button>\r\n");
      out.write("                    <div class=\"profilebox-body\">\r\n");
      out.write("                        <form action=\"/member/join.do\" method=\"post\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"profile-modal-p\">닉네임</p>\r\n");
      out.write("                                <input id=\"profile-nickname\" name=\"memName\" placeholder=\"안녕하세요\">\r\n");
      out.write("                                <p class=\"profile-message\" id=\"nickname-message\">default</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div style=\"margin-top: 1vh;\">\r\n");
      out.write("                                <p class=\"profile-modal-p\">현재 비밀번호</p>\r\n");
      out.write("                                <input id=\"origin-password\" name=\"password\" type=\"password\" placeholder=\"사용 중인 비밀번호를 입력해주세요.\">\r\n");
      out.write("                                <p class=\"profile-message\" id=\"password-message\">default</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div style=\"margin-top: 1vh;\">\r\n");
      out.write("                                <p class=\"profile-modal-p\">새 비밀번호</p>\r\n");
      out.write("                                <input id=\"newpassword\" type=\"password\" placeholder=\"새로운 비밀번호를 입력해주세요.\">\r\n");
      out.write("                                <p class=\"profile-message\" id=\"newpassword-message\">default</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div style=\"margin-top: 1vh;\">\r\n");
      out.write("                                <p class=\"profile-modal-p\">새 비밀번호 확인</p>\r\n");
      out.write("                                <input id=\"newpassword-check\" type=\"password\" placeholder=\"한 번 더 입력해주세요.\">\r\n");
      out.write("                                <p class=\"profile-message\" id=\"newpassword-check-message\">default</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div style=\"margin-top: 2vh; background: #23C961; width: 20vw; height: 7vh; border-radius: 5px; display: flex; justify-content: center\">\r\n");
      out.write("                                <button type=\"submit\" id=\"save-modify-btn\" style=\"color: white; font-size: 1.3em\">변경사항 저장</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            let originNickname = \"카리나\";\r\n");
      out.write("            let nickname = \"\";\r\n");
      out.write("            let originPassword = \"\";\r\n");
      out.write("            let newPassword = \"\";\r\n");
      out.write("            let newPasswordCheck = \"\";\r\n");
      out.write("            // 정규표현식\r\n");
      out.write("            const regex = /^(?=.*[a-zA-Z])(?=.*[!@#$%^&*+=-])(?=.*[0-9]).{8,15}$/;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("                const popupIcon = document.getElementById('popup-icon1');\r\n");
      out.write("                const popupContent = document.getElementById('popup-content1');\r\n");
      out.write("                const popupIcon2 = document.getElementById('popup-icon2');\r\n");
      out.write("\r\n");
      out.write("                popupIcon.addEventListener('mouseover', () => {\r\n");
      out.write("                    popupContent.classList.remove('hidden');\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                popupIcon.addEventListener('mouseleave', () => {\r\n");
      out.write("                    popupContent.classList.add('hidden');\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                popupIcon2.addEventListener('click', () => {\r\n");
      out.write("                    window.scrollTo({ top: 0, behavior: 'smooth' });\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(() => {\r\n");
      out.write("                $(\"#mycontentbtn\").addClass(\"active\");\r\n");
      out.write("                $(\".mycontenttxt\").css(\"color\", \"white\");\r\n");
      out.write("                $(\"#mycontentbtn\").click((e) => {\r\n");
      out.write("                    $(\"#mycontentbtn\").addClass(\"active\");\r\n");
      out.write("                    $(\"#snscontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#shopcontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#contype\").trigger(\"click\");\r\n");
      out.write("                    $(\".mycontenttxt\").css(\"color\", \"white\");\r\n");
      out.write("                    $(\".snspic\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".myshopping\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\"#content-a\").show();\r\n");
      out.write("                    $(\"#content-b\").hide();\r\n");
      out.write("                    $(\"#content-c\").hide();\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#snscontentbtn\").click((e) => {\r\n");
      out.write("                    $(\"#mycontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#snscontentbtn\").addClass(\"active\");\r\n");
      out.write("                    $(\"#shopcontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#snstype\").trigger(\"click\");\r\n");
      out.write("                    $(\".mycontenttxt\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".snspic\").css(\"color\", \"white\");\r\n");
      out.write("                    $(\".myshopping\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\"#content-a\").hide();\r\n");
      out.write("                    $(\"#content-b\").show();\r\n");
      out.write("                    $(\"#content-c\").hide();\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#shopcontentbtn\").click((e) => {\r\n");
      out.write("                    $(\"#mycontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#snscontentbtn\").removeClass(\"active\");\r\n");
      out.write("                    $(\"#shopcontentbtn\").addClass(\"active\");\r\n");
      out.write("                    $(\"#shoptype\").trigger(\"click\");\r\n");
      out.write("                    $(\".mycontenttxt\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".snspic\").css(\"color\", \"#27AF5A\");\r\n");
      out.write("                    $(\".myshopping\").css(\"color\", \"white\");\r\n");
      out.write("                    $(\"#content-a\").hide();\r\n");
      out.write("                    $(\"#content-b\").hide();\r\n");
      out.write("                    $(\"#content-c\").show();\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#profile-nickname\").on(\"change\", (e) => {\r\n");
      out.write("                    nickname = e.target.value;\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#profile-nickname\").on(\"blur\", (e) => {\r\n");
      out.write("                    if(nickname !== \"\"){\r\n");
      out.write("                        if(nickname === originNickname) {\r\n");
      out.write("                            $(\"#nickname-message\").css({\r\n");
      out.write("                                \"visibility\": \"visible\", \"color\": \"red\"\r\n");
      out.write("                            }).text(\"중복된 닉네임입니다.\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#nickname-message\").css({\r\n");
      out.write("                                \"visibility\": \"visible\", \"color\": \"green\"\r\n");
      out.write("                            }).text(\"사용 가능한 닉네임입니다.\");\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#nickname-message\").css({\"visibility\": \"hidden\"});\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#origin-password\").on(\"change\", (e) => {\r\n");
      out.write("                    originPassword = e.target.value;\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#origin-password\").on(\"blur\", (e) => {\r\n");
      out.write("                    if(originPassword === \"\") {\r\n");
      out.write("                        $(\"#password-message\").css({\"visibility\": \"hidden\"});\r\n");
      out.write("                    } else {\r\n");
      out.write("                        if(originPassword !== \"12345678\"){\r\n");
      out.write("                            $(\"#password-message\").css({\r\n");
      out.write("                                \"visibility\": \"visible\", \"color\": \"red\"\r\n");
      out.write("                            }).text(\"이전 비밀번호와 일치하지 않습니다.\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#password-message\").css({\r\n");
      out.write("                                \"visibility\": \"visible\", \"color\": \"green\"\r\n");
      out.write("                            }).text(\"이전 비밀번호와 일치합니다.\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#newpassword\").on(\"change\", (e) => {\r\n");
      out.write("                    newPassword = e.target.value;\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#newpassword\").on(\"blur\", (e) => {\r\n");
      out.write("                    if(newPassword === \"\") {\r\n");
      out.write("                        $(\"#newpassword-message\").css({\"visibility\": \"hidden\"});\r\n");
      out.write("                    } else {\r\n");
      out.write("                        if(!regex.test(newPassword)) {\r\n");
      out.write("                            $(\"#newpassword-message\").css({\r\n");
      out.write("                                \"visibility\": \"visible\", \"color\": \"red\"\r\n");
      out.write("                            }).text(\"비밀번호는 영문 숫자 특수기호 포함 8자리 이상으로 지정해주세요.\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#newpassword-message\").css({\r\n");
      out.write("                                \"visibility\": \"hidden\"});\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#newpassword-check\").on(\"change\", (e) => {\r\n");
      out.write("                    newPasswordCheck = e.target.value;\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $(\"#newpassword-check\").on(\"blur\", (e) => {\r\n");
      out.write("                    if(newPasswordCheck === \"\") {\r\n");
      out.write("                        $(\"#newpassword-check-message\").css({\"visibility\": \"hidden\"});\r\n");
      out.write("                    } else {\r\n");
      out.write("                        if(newPassword !== newPasswordCheck) {\r\n");
      out.write("                            $(\"#newpassword-check-message\").css({\r\n");
      out.write("                                \"visibility\": \"visible\", \"color\": \"red\"\r\n");
      out.write("                            }).text(\"입력한 비밀번호와 다릅니다.\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#newpassword-check-message\").css({\r\n");
      out.write("                                \"visibility\": \"hidden\"});\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#save-modify-btn\").click((e) => {\r\n");
      out.write("                    if(nickname !== originNickname && originPassword === \"12345678\" &&\r\n");
      out.write("                        regex.test(newPassword) === true && newPassword === newPasswordCheck) {\r\n");
      out.write("                        alert(\"전송 성공\");\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(\"전송 실패\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
